export const KYSELY_MODULE_CONNECTION_TOKEN = "KYSELY_MODULE";
export const KYSELY_MODULE_CONFIG_TOKEN = "KYSELY_MODULE_CONFIG_TOKEN";

export const ENV_DATABASE_URI = "DATABASE_URI";

export const ENV_FILE_PATHS = [".env"];
